### ISSUE TITLE
index out of range

### ISSUE THREAD

**Issue by arj03** [dominictarr/flume-repair-log#1]
I tried running the command but get the following error:

chrx@chrx:~/.ssb/flume$ flume-repair-log log.offset 
buffer.js:839
    throw new RangeError('Index out of range');
    ^

RangeError: Index out of range
    at checkOffset (buffer.js:839:11)
    at Buffer.readUInt32BE (buffer.js:913:5)
    at /home/chrx/.nvm/versions/node/v7.8.0/lib/node_modules/flume-repair-log/node_modules/aligned-block-file/blocks.js:90:29
    at /home/chrx/.nvm/versions/node/v7.8.0/lib/node_modules/flume-repair-log/node_modules/aligned-block-file/blocks.js:34:36
    at /home/chrx/.nvm/versions/node/v7.8.0/lib/node_modules/flume-repair-log/node_modules/aligned-block-file/file.js:45:13
    at FSReqWrap.wrapper [as oncomplete] (fs.js:629:17)

**Comment by dominictarr** [comment]
hmm, so it's reading past the end of the log? does this happen immediately or does it process lots of stuff before erroring?

one thing that might help quickly, though is post the output of:

```
tail -c 1024 ~/.ssb/flume/log.offset  | hexdump -C
```

Otherwise you might have to give me a copy of the log file, or add debugging logs near the stack trace methods.

**Comment by arj03** [comment]
00000000  36 4a 47 4b 62 57 36 37  76 78 7a 44 51 3d 3d 2e  |6JGKbW67vxzDQ==.|
00000010  73 69 67 2e 65 64 32 35  35 31 39 22 7d 2c 22 74  |sig.ed25519"},"t|
00000020  69 6d 65 73 74 61 6d 70  22 3a 31 34 39 38 34 31  |imestamp":149841|
00000030  38 36 35 31 39 35 30 2e  30 31 33 7d 00 00 01 e0  |8651950.013}....|
00000040  06 d3 ff 6c 00 00 01 d6  7b 22 6b 65 79 22 3a 22  |...l....{"key":"|
00000050  25 75 67 39 30 6e 4e 65  64 62 4c 50 65 55 78 56  |%ug90nNedbLPeUxV|
00000060  38 58 47 46 4a 32 6b 32  71 45 6d 73 47 79 33 69  |8XGFJ2k2qEmsGy3i|
00000070  49 2b 61 6b 39 4e 6b 43  6a 4b 5a 67 3d 2e 73 68  |I+ak9NkCjKZg=.sh|
00000080  61 32 35 36 22 2c 22 76  61 6c 75 65 22 3a 7b 22  |a256","value":{"|
00000090  70 72 65 76 69 6f 75 73  22 3a 22 25 4d 69 45 6a  |previous":"%MiEj|
000000a0  46 4a 51 5a 64 6c 52 65  45 50 32 69 64 34 5a 44  |FJQZdlReEP2id4ZD|
000000b0  2f 76 30 55 4c 52 64 2f  4c 42 75 41 4d 4b 48 75  |/v0ULRd/LBuAMKHu|
000000c0  66 79 59 41 36 49 63 3d  2e 73 68 61 32 35 36 22  |fyYA6Ic=.sha256"|
000000d0  2c 22 61 75 74 68 6f 72  22 3a 22 40 6e 45 6f 76  |,"author":"@nEov|
000000e0  78 71 44 49 44 5a 4a 63  64 42 49 77 6c 4d 2b 66  |xqDIDZJcdBIwlM+f|
000000f0  4c 4e 6c 47 43 47 45 33  32 61 72 32 46 2b 4f 31  |LNlGCGE32ar2F+O1|
00000100  72 6e 38 51 58 4e 30 3d  2e 65 64 32 35 35 31 39  |rn8QXN0=.ed25519|
00000110  22 2c 22 73 65 71 75 65  6e 63 65 22 3a 35 32 2c  |","sequence":52,|
00000120  22 74 69 6d 65 73 74 61  6d 70 22 3a 31 34 39 38  |"timestamp":1498|
00000130  34 31 35 32 35 31 35 31  38 2c 22 68 61 73 68 22  |415251518,"hash"|
00000140  3a 22 73 68 61 32 35 36  22 2c 22 63 6f 6e 74 65  |:"sha256","conte|
00000150  6e 74 22 3a 7b 22 74 79  70 65 22 3a 22 63 68 61  |nt":{"type":"cha|
00000160  6e 6e 65 6c 22 2c 22 63  68 61 6e 6e 65 6c 22 3a  |nnel","channel":|
00000170  22 73 70 61 63 65 78 22  2c 22 73 75 62 73 63 72  |"spacex","subscr|
00000180  69 62 65 64 22 3a 74 72  75 65 7d 2c 22 73 69 67  |ibed":true},"sig|
00000190  6e 61 74 75 72 65 22 3a  22 73 62 75 50 65 78 45  |nature":"sbuPexE|
000001a0  4f 6d 4e 6f 76 45 61 77  32 5a 47 46 30 48 75 71  |OmNovEaw2ZGF0Huq|
000001b0  71 30 65 7a 45 73 30 46  41 56 46 30 71 58 4f 67  |q0ezEs0FAVF0qXOg|
000001c0  43 39 6c 43 6a 59 64 77  2b 57 4a 62 5a 69 46 39  |C9lCjYdw+WJbZiF9|
000001d0  38 2f 61 34 50 76 6d 6e  6c 73 4d 5a 48 67 34 78  |8/a4PvmnlsMZHg4x|
000001e0  7a 6c 65 62 44 49 74 49  33 56 6f 33 41 41 51 3d  |zlebDItI3Vo3AAQ=|
000001f0  3d 2e 73 69 67 2e 65 64  32 35 35 31 39 22 7d 2c  |=.sig.ed25519"},|
00000200  22 74 69 6d 65 73 74 61  6d 70 22 3a 31 34 39 38  |"timestamp":1498|
00000210  34 31 38 36 35 31 39 35  30 2e 30 31 34 7d 00 00  |418651950.014}..|
00000220  01 d6 06 d4 01 4e 00 00  01 ce 7b 22 6b 65 79 22  |.....N....{"key"|
00000230  3a 22 25 4b 39 4b 35 48  30 52 59 4b 74 49 75 54  |:"%K9K5H0RYKtIuT|
00000240  52 65 69 4e 57 33 54 41  4f 72 66 36 72 7a 70 39  |ReiNW3TAOrf6rzp9|
00000250  64 7a 46 64 6f 45 54 64  32 64 6a 78 4b 55 3d 2e  |dzFdoETd2djxKU=.|
00000260  73 68 61 32 35 36 22 2c  22 76 61 6c 75 65 22 3a  |sha256","value":|
00000270  7b 22 70 72 65 76 69 6f  75 73 22 3a 6e 75 6c 6c  |{"previous":null|
00000280  2c 22 61 75 74 68 6f 72  22 3a 22 40 69 79 49 4b  |,"author":"@iyIK|
00000290  4e 6a 70 39 79 56 4d 31  33 4e 48 2b 42 67 43 64  |Njp9yVM13NH+BgCd|
000002a0  74 46 50 67 53 74 2f 76  37 64 31 45 77 6a 6c 61  |tFPgSt/v7d1Ewjla|
000002b0  55 52 76 48 63 41 49 3d  2e 65 64 32 35 35 31 39  |URvHcAI=.ed25519|
000002c0  22 2c 22 73 65 71 75 65  6e 63 65 22 3a 31 2c 22  |","sequence":1,"|
000002d0  74 69 6d 65 73 74 61 6d  70 22 3a 31 34 39 38 34  |timestamp":14984|
000002e0  30 30 38 38 35 32 34 37  2c 22 68 61 73 68 22 3a  |00885247,"hash":|
000002f0  22 73 68 61 32 35 36 22  2c 22 63 6f 6e 74 65 6e  |"sha256","conten|
00000300  74 22 3a 7b 22 74 79 70  65 22 3a 22 61 62 6f 75  |t":{"type":"abou|
00000310  74 22 2c 22 61 62 6f 75  74 22 3a 22 40 69 79 49  |t","about":"@iyI|
00000320  4b 4e 6a 70 39 79 56 4d  31 33 4e 48 2b 42 67 43  |KNjp9yVM13NH+BgC|
00000330  64 74 46 50 67 53 74 2f  76 37 64 31 45 77 6a 6c  |dtFPgSt/v7d1Ewjl|
00000340  61 55 52 76 48 63 41 49  3d 2e 65 64 32 35 35 31  |aURvHcAI=.ed2551|
00000350  39 22 2c 22 6e 61 6d 65  22 3a 22 6d 61 67 69 63  |9","name":"magic|
00000360  61 64 75 22 7d 2c 22 73  69 67 6e 61 74 75 72 65  |adu"},"signature|
00000370  22 3a 22 2f 6a 30 61 2f  4a 72 67 63 4f 65 6c 55  |":"/j0a/JrgcOelU|
00000380  75 43 35 48 52 73 38 6c  73 6f 35 75 70 45 34 44  |uC5HRs8lso5upE4D|
00000390  58 45 42 46 2b 51 6a 54  6e 52 4d 61 55 4b 75 32  |XEBF+QjTnRMaUKu2|
000003a0  5a 56 64 48 62 53 47 74  59 57 4b 59 4e 4d 52 75  |ZVdHbSGtYWKYNMRu|
000003b0  6f 43 30 2b 61 75 6f 6c  2f 5a 31 6d 38 44 77 68  |oC0+auol/Z1m8Dwh|
000003c0  45 6a 42 4d 62 6e 6f 44  67 3d 3d 2e 73 69 67 2e  |EjBMbnoDg==.sig.|
000003d0  65 64 32 35 35 31 39 22  7d 2c 22 74 69 6d 65 73  |ed25519"},"times|
000003e0  74 61 6d 70 22 3a 31 34  39 38 34 31 38 36 35 31  |tamp":1498418651|
000003f0  39 35 30 2e 30 31 35 7d  00 00 01 ce 06 d4 03 28  |950.015}.......(|
00000400

It isn't the worlds worst bug as I'm not sure if my flume db is corrupt or not, I just wanted to be sure and ran the command.

**Comment by dominictarr** [comment]
oh, that file is already using the new version. so no need to migrate, you only needed to run this if you where using the flume branch of ssb before 10.0.0 if everything is working for you normally, you shouldn't need to do anything.

**Comment by arj03** [comment]
I see. Sorry for the noise then.
